name: Deploy via SSH

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy to server via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # optional ssh port
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_PATH }}
            git pull
            docker compose up -d --build
